services:
  fastapi-server:
    container_name: fastapi
    image: kimhongseok/fastapi-app:v1.0.2
    ports:
      - "8000:8000"
    networks:
      - teamEnet
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    container_name: mongo
    image: mongo:latest
    command: mongod --noauth  # 인증 비활성화 플래그 추가
    volumes:
      - mongodb_data:/data/db
    networks:
      - teamEnet
    environment: {}

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    networks:
      - teamEnet

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - teamEnet

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - teamEnet
    depends_on:
      - prometheus

networks:
  teamEnet:
    driver: bridge

volumes:
  mongodb_data:


