name: CD

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 서버에 배포
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |

            # Docker Compose 파일에서 이미지를 최신 태그로 업데이트
          #  sed -i "s|image:.*|image: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:${{ secrets.DOCKER_IMAGE_TAG }}|" docker-compose.yml

            # 기존 컨테이너 중지 및 제거
            docker-compose down || true

            # 최신 이미지 다운로드
            docker-compose pull

            # 새로운 컨테이너 실행
            docker-compose up -d

            echo "Deployment complete."
